(in-package :thnappy)

(defun compress-string (string)
  (with-foreign-pointer (compr (snappy-max-compressed-length (length string)))
    (with-foreign-object (compr-size 'size-t)
      (with-foreign-string (cstring string)
        (ecase (snappy-compress cstring (length string) compr compr-size)
          (:ok t)
          (:invalid-input (error "Invalid input!"))
          (:buffer-too-small (error "Buffer too small!")))
        (let* ((size (cffi:mem-ref compr-size 'size-t))
               (result (make-array size :element-type '(unsigned-byte 8))))
          (mem-read-vector result compr :uchar size)
          result)))))

(defun compress-vector (bytes)
  (let ((bytes-length (length bytes)))
    (with-foreign-pointer (compr (snappy-max-compressed-length bytes-length))
      (with-foreign-objects ((compr-size 'size-t)
                             (c-bytes :uchar bytes-length))
        (mem-write-vector bytes c-bytes :uchar)
        (ecase (snappy-compress c-bytes bytes-length compr compr-size)
          (:ok t)
          (:invalid-input (error "Invalid input!"))
          (:buffer-too-small (error "Buffer to small!")))
        (let* ((size (cffi:mem-ref compr-size 'size-t))
               (result (make-array size :element-type '(unsigned-byte 8))))
          (mem-read-vector result compr :uchar size)
          result)) )))

(defun uncompress-vector (compressed-bytes)
  (let ((byte-count (length compressed-bytes)))
    (with-foreign-objects ((uncompr-size 'size-t)
                           (c-compr-bytes :uchar byte-count))
      (mem-write-vector compressed-bytes c-compr-bytes :uchar)
      (ecase (snappy-uncompressed-length c-compr-bytes byte-count uncompr-size)
        (:ok t)
        (:invalid-input (error "Invalid input!"))
        (:buffer-too-small (error "Buffer to small!")))
      (with-foreign-pointer
          (uncompr (mem-ref uncompr-size 'size-t) uncompressed-size)
        (ecase (snappy-uncompress c-compr-bytes byte-count uncompr uncompr-size)
          (:ok t)
          (:invalid-input (error "Invalid input!"))
          (:buffer-too-small (error "Buffer to small!")))
        (let* ((size (cffi:mem-ref uncompr-size 'size-t))
               (result (make-array size :element-type '(unsigned-byte 8))))
          (assert (= size uncompressed-size))
          (mem-read-vector result uncompr :uchar size)
          result)) )))

(defun valid-compressed-p (bytes)
  (with-foreign-pointer (compressed-bytes (length bytes) byte-count)
    (mem-write-vector bytes compressed-bytes :uchar)
    (ecase (snappy-validate-compressed-buffer compressed-bytes (length bytes))
      (:ok t)
      (:invalid-input (error "Invalid input!"))
      (:buffer-too-small (error "Buffer too small!")))))
